# Site settings
title: Biplab Paul
general_email: paul202b@gmail.com
academic_email: bpaul5@mgh.harvard.edu

description: > # this means to ignore newlines until "baseurl:"
  I am a scientist with a passion to serve developing nation in building their science capacity.

#baseurl: "biplabua.github.io" # the subpath of your site, e.g. /blog/

url: "https://biplabua.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: biplabua
linkedin_username: biplab-paul-9365b8105
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
